<html html>
	<head>
  		<title>Vehicle Report</title>
		<style>
		  	h1, h2, h3, h4, h5, h6 {
				  font-family: arial, sans-serif;
			  }
			table {
					font-family: arial, sans-serif;
					border-collapse: collapse;
					width: 100%;
					font-size: 10px;
					border: 1px solid #000;
				}

			th, td {
					width: 25%;
					text-align: left;
					vertical-align: top;
					border: 1px solid #000;
					border-collapse: collapse;
					padding: 0.3em;
					caption-side: bottom;
					height: 20px;
			}

			th {
				background-color: #595555;
				color: white;
				font-size: 10px;
				width: 100%;
			}
			img{
			}
			
		</style>
	</head>
	<body>
		<center>
			<img align="center" src="{{ $imagen}}" alt="" height="100">
		</center>
		<h4 align="center">
			<strong><u>Vehicles List</u></strong>
		</h4>
		<h6>
			<strong>Date:</strong><font color="Blue"> <strong>'{{ $hoy}}' </strong></font>
			<br><strong>Company:</strong><font color="Blue"> <strong>'{{ $empresa}}' </strong></font>
			<br><strong>Report created by:</strong><font color="Blue"> <strong>'{{ $nombreusu}}' <strong></font>
			
		</h6>
		<table>
			<tr>		
				<th>#Vehicle</th>
				<th>No. Plate</th>
				<th>Other ID</th>
				<th>Type</th>
				<th>Make/Model/Year/Capacity</th>
				<th>Additional Licencing</th>
				<th>Status</th>
			</tr>
			@foreach ($vehicles as $vehi)
			<tr>
				<td><h4 align="center">{{ $vehi->number_vehicle}}</h4></td>
				<td><h4 align="center">{{ $vehi->no_plate}}</h4></td>
				<td><h4 align="center">{{ $vehi->other_id}}</h4></td>
				<td><h4 align="center">{{ $vehi->type}} / {{$vehi->trailer_or_unit_type}} </h4></td>
				<td><h4 align="center">{{ $vehi->make }} / {{ $vehi->model }} / {{ $vehi->year }} / {{ $vehi->capacity }}</h4></td>
				<td><h4 align="center">{{ $vehi->oregon_weight}}</h4></td>
				<td><h4 align="center">{{ $vehi->state_vehicle}}</h4></td>
			</tr>
			@endforeach
		</table>
		<br>
		<h6>Report generated by: <a href="https://szystems.com/" target="_blank">Szystems Version 1.0</a> &copy; 2021 <a class="link-muted" href="https://szystems.com/" target="_blank">Szystems</a>. All rights reserved.</h6>
	</body>
</html>