<html html>
	<head>
  		<title>Vehicle Report</title>
		<style>
		  	h1, h2, h3, h4, h5, h6 {
				  font-family: arial, sans-serif;
			  }
			table {
					font-family: arial, sans-serif;
					border-collapse: collapse;
					width: 50%;
					font-size: 10px;
					border: 1px solid #000;
				}

			th, td {
					width: 25%;
					text-align: left;
					vertical-align: top;
					border: 1px solid #000;
					border-collapse: collapse;
					padding: 0.3em;
					caption-side: bottom;
					height: 20px;
			}

			th {
				background-color: #595555;
				color: white;
				font-size: 10px;
				width: 100%;
			}
			img{
			}
			
		</style>
	</head>
	<body>
		@if ($imagen != null)
			<center>
				<img align="center" src="{{ $imagen}}" alt="" height="100">
			</center>
		@endif
		<h4 align="center">
			<strong><u>Vehicle View</u></strong>
		</h4>
		<h6>
			<strong>Date:</strong><font color="Blue"> <strong>'{{ $hoy}}' </strong></font>
			<br><strong>Company:</strong><font color="Blue"> <strong>'{{ $empresa}}' </strong></font>
			<br><strong>User:</strong><font color="Blue"> <strong>'{{ $nombreusu}}' <strong></font>
			
		</h6>
		<div style="text-align:center;">
		<table>
			<tr>		
				<th colspan="2"><h4 align="center">{{ $vehicle->number_vehicle}}</h4></th>
			</tr>
			<tr>
				<td><h4 align="right"><strong>Other ID:</strong></h4></td>
				<td><h4 align="left"><font color="Blue">{{ $vehicle->other_id}}</font></h4></td>
			</tr>
			<tr>
				<td><h4 align="right"><strong>Make:</strong></h4></td>
				<td><h4 align="left"><font color="Blue">{{ $vehicle->make}}</font></h4></td>
			</tr>
			<tr>
				<td><h4 align="right"><strong>Model:</strong></h4></td>
				<td><h4 align="left"><font color="Blue">{{ $vehicle->model}}</font></h4></td>
			</tr>
			<tr>
				<td><h4 align="right"><strong>Year:</strong></h4></td>
				<td><h4 align="left"><font color="Blue">{{ $vehicle->year}}</font></h4></td>
			</tr>
			<tr>
				<td><h4 align="right"><strong>Capacity:</strong></h4></td>
				<td><h4 align="left"><font color="Blue">{{ $vehicle->capacity}}</font></h4></td>
			</tr>
			<tr>
				<td><h4 align="right"><strong>Type:</strong></h4></td>
				<td><h4 align="left"><font color="Blue">{{$vehicle->type}} / {{$vehicle->trailer_or_unit_type}} f</font></h4></td>
			</tr>
			<tr>
				<td><h4 align="right"><strong>No. Plate:</strong></h4></td>
				<td><h4 align="left"><font color="Blue">{{ $vehicle->no_plate}}</font></h4></td>
			</tr>
			<tr>
				<td><h4 align="right"><strong>Additional Licencing:</strong></h4></td>
				<td><h4 align="left"><font color="Blue">{{ $vehicle->oregon_weight}}</font></h4></td>
			</tr>
			<tr>
				<td><h4 align="right"><strong>State:</strong></h4></td>
				<td><h4 align="left"><font color="Blue">{{ $vehicle->state_vehicle}}</font></h4></td>
			</tr>
			
		</table>
		</div>
		
		<br>
		<h6>Report generated by: <a href="https://szystems.com/" target="_blank">Szystems Version 1.0</a> &copy; 2021 <a class="link-muted" href="https://szystems.com/" target="_blank">Szystems</a>. All rights reserved.</h6>
	</body>
</html>