<html html>
	<head>
  		<title>User Report</title>
		<style>
		  	h1, h2, h3, h4, h5, h6 {
				  font-family: arial, sans-serif;
			  }
			table {
					font-family: arial, sans-serif;
					border-collapse: collapse;
					width: 50%;
					font-size: 10px;
					border: 1px solid #000;
				}

			th, td {
					width: 25%;
					text-align: left;
					vertical-align: top;
					border: 1px solid #000;
					border-collapse: collapse;
					padding: 0.3em;
					caption-side: bottom;
					height: 20px;
			}

			th {
				background-color: #595555;
				color: white;
				font-size: 10px;
				width: 100%;
			}
			img{
			}
			
		</style>
	</head>
	<body>
		@if ($imagen != null)
			<center>
				<img align="center" src="{{ $imagen}}" alt="" height="100">
			</center>
		@endif
		<h4 align="center">
			<strong><u>User View</u></strong>
		</h4>
		<h6>
			<strong>Date:</strong><font color="Blue"> <strong>'{{ $hoy}}' </strong></font>
			<br><strong>Company:</strong><font color="Blue"> <strong>'{{ $empresa}}' </strong></font>
			<br><strong>User:</strong><font color="Blue"> <strong>'{{ $nombreusu}}' <strong></font>
			
		</h6>
		<div style="text-align:center;">
		<table>
			<tr>		
				<th colspan="2"><h4 align="center">{{ $usuario->name}}</h4></th>
			</tr>
			<?php
                $birthday = date("m-d-Y", strtotime($usuario->birthday));

                $birth = new DateTime($usuario->birthday);
                $today = new DateTime();
                $years = $today->diff($birth);
                $age = $years->y;
            ?>
			<tr>
				<td><h4 align="right"><strong>Birthday:</strong></h4></td>
				<td><h4 align="left"><font color="Blue">{{ $birthday}} (Age: {{$age}})</font></h4></td>
			</tr>
			<tr>
				<td><h4 align="right"><strong>Address:</strong></h4></td>
				<td><h4 align="left"><font color="Blue">{{ $usuario->address}}</font></h4></td>
			</tr>
			<tr>
				<td><h4 align="right"><strong>Phone:</strong></h4></td>
				<td><h4 align="left"><font color="Blue">{{ $usuario->phone}}</font></h4></td>
			</tr>
			<tr>
				<td><h4 align="right"><strong>Email:</strong></h4></td>
				<td><h4 align="left"><font color="Blue">{{ $usuario->email}}</font></h4></td>
			</tr>
			<tr>
				<td><h4 align="right"><strong>Driver License Number:</strong></h4></td>
				<td><h4 align="left"><font color="Blue">{{ $usuario->driver_license_number}}</font></h4></td>
			</tr>
			<?php
                $expiration = date("m-d-Y", strtotime($usuario->expiration_day));
            ?>
			<tr>
				<td><h4 align="right"><strong>Expiration Day:</strong></h4></td>
				<td><h4 align="left"><font color="Blue">{{ $expiration}}</font></h4></td>
			</tr>
			<tr>
				<td><h4 align="right"><strong>Issuing State:</strong></h4></td>
				<td><h4 align="left"><font color="Blue">{{ $usuario->issuing_state}}</font></h4></td>
			</tr>
			<tr>
				<td><h4 align="right"><strong>SSN:</strong></h4></td>
				@isset($usuario->ssn)
				<?php   
                    $SSN = substr($usuario->ssn, 7);
                ?>
				<td><h4 align="left"><font color="Blue">XXX-XX-{{$SSN}}</font></h4></td>
				@endisset
			</tr>
			@if ($usuario->license_image != null)
			<tr>
				<td><h4 align="right"><strong>License Image:</strong></h4></td>
				<td><img align="center" src="{{$path.$usuario->license_image}}" alt="" height="150"></td>
			</tr>
			@endif
            @if ($usuario->medical_card_image != null)
			<tr>
				<td><h4 align="right"><strong>Medical Card Image:</strong></h4></td>
				<td><img align="center" src="{{$path.$usuario->medical_card_image}}" alt="" height="150"></td>
			</tr>
			@endif
			
		</table>
		</div>
		<br>
		<div style="text-align:center;">
		<table>
			<tr>		
				<th colspan="2"><h4 align="center">Security and Settings</h4></th>
			</tr>
			<tr>
				<td><h4 align="right"><strong>Principal:</strong></h4></td>
				<td><h4 align="left"><font color="Blue">{{ $usuario->principal}}</font></h4></td>
			</tr>
			<tr>
				<td><h4 align="right"><strong>Type:</strong></h4></td>
				<td><h4 align="left"><font color="Blue">{{ $usuario->user_type}}</td>
			</tr>
		</table>
		</div>
		<br>
		<h6>Report generated by: <a href="https://szystems.com/" target="_blank">Szystems Version 1.0</a> &copy; 2021 <a class="link-muted" href="https://szystems.com/" target="_blank">Szystems</a>. All rights reserved.</h6>
	</body>
</html>